import flat from 'flat';

const en_US = {
  base: {
    cancel: '取消',
    loadMore: '加載更多',
    logout: '登 出',
    reconnect: '重連中',
  },
  Address: {
    NoMoreAddress: '已沒有更多',
    Search: '搜索',
    ShowAddressMore: '當前顯示成員較多，建議您使用搜索功能尋找同事',
  },
  Dialogue: {
    MentionName: '標註人名',
    Cancel: '取消',
    Finish: '確定',
    groupDynamics: '群組',
    personalDynamics: '個人動態',
    personalIdentity: '個人身份',
    adminIdentity: '管理員身份',
  },
  Post: {
    addNew: '新增動態',
    thinkingAboutSomething: '在想些什麼?',
    createPost: '建立貼文',
    leaveWord: '留個言吧....',
    And: '和',
    And2: '及',
    OtherPeople: '其他 {count} 人',
    Like: '讚好',
    Liked: '已讚好',
    Reply: '回覆',
    NoDynamic: '暫未有最新動態',
    Edit: '編輯',
  },
  Group: {
    CreateGroup: '建立群組',
    ExplorationGroup: '探索群組',
    FastEntry: '群組捷徑',
    GroupMember: '群組成員',
    PublicGroup: '公開群組',
    SecretGroup: '秘密群組',
    MemberCount: '{count}位成員',
    FansCount: '{count}位粉絲',
    TrackingGroup: '追蹤群組',
    YouGroup: '你的群組',
    GroupNamePlaceholder: '名稱',
    HeadPortrait: '群組頭像',
    PrivacySettings: '私隱設定',
    Public: '公開',
    Secret: '秘密',
    CreateGroupFont: '確認創建',
    NewsMembers: '成員',
    NewsAddMembers: '新增成員',
    ExploreGroup: '追蹤更多',
    GroupFan: '群組粉絲',
    invitation: '邀請',
    leave: '退出',
    exitGroup: '退出群組',
    exitGroupConfirm: `確定退出 {name} 嗎？`,
    definiteExit: '確定退出',
    groupSetup: '群組設置',
    defaultGroupCannotExit: '預設群組不能退出',
    acceptingInvitation: '接受邀請',
    refuseInvitation: '不接受邀請',
    notice: '通知',
    seeMore: '查看更多…',
  },
  Message: {
    FollowSuccess: '追蹤成功',
  },
  follow: {
    follow: '追蹤',
    followed: '追蹤中',
  },
  Login: {
    UserOrEmail: '用戶名稱或電郵地址',
    Password: '密碼',
    PleaseContact: '請致電 8891 1234 聯絡IT 24 小時熱線協助重設密碼',
    Forget_password: '忘記密碼',
    Login: '登   入',
    UnderDevelopment: '此功能暫未開放',
    IfYou: '若取消選取此選項，SunPeople 網頁版將於數分鐘休止狀態後自動登出。',
    KeepLogged: '保持登录狀態',
    Please_WIFI: '為减少閣下流動電話的數據使用量請連接到閣下的無線網絡',
    LoginPrompt: '登入資料錯誤，請重新輸入並登入',
    PleaseWait: '登入中，請稍後。。。',
  },
  panel: {
    allDynamics: '全部動態',
    group: '群組',
  },
};
export default flat(en_US);
